name: release

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - uses: actions/checkout@v3

      - name: Get php version
        run: php -v

      - name: Get version
        run: echo ${{ github.event.release.tag_name }}

      - name: Build phar
        run: php -d phar.readonly=0 bin/build -v"${{ github.event.release.tag_name }}"

      - name: Verify version
        run: php docker-ws.phar -V

      - name: Upload phar
        run: gh release upload v"${{ github.event.release.tag_name }}" docker-ws.phar
        env:
          GH_TOKEN: ${{ github.token }}

